# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interaction.proto',
  package='interaction',
  syntax='proto3',
  serialized_options=b'\n!com.interaction.robot.interactionB\rInteractProtoP\001\242\002\002ST',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11interaction.proto\x12\x0binteraction\" \n\x0e\x43onnectRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1e\n\x0c\x43onnectReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1a\n\x05Input\x12\x11\n\tutterance\x18\x01 \x01(\t\"\x1b\n\x06Output\x12\x11\n\tutterance\x18\x01 \x01(\t2\x8e\x01\n\x08Interact\x12I\n\rSimpleConnect\x12\x1b.interaction.ConnectRequest\x1a\x19.interaction.ConnectReply\"\x00\x12\x37\n\nSimpleSend\x12\x12.interaction.Input\x1a\x13.interaction.Output\"\x00\x42\x39\n!com.interaction.robot.interactionB\rInteractProtoP\x01\xa2\x02\x02STb\x06proto3'
)




_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='interaction.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='interaction.ConnectRequest.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=66,
)


_CONNECTREPLY = _descriptor.Descriptor(
  name='ConnectReply',
  full_name='interaction.ConnectReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='interaction.ConnectReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=98,
)


_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='interaction.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='utterance', full_name='interaction.Input.utterance', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=126,
)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='interaction.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='utterance', full_name='interaction.Output.utterance', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectReply'] = _CONNECTREPLY
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectReply = _reflection.GeneratedProtocolMessageType('ConnectReply', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREPLY,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.ConnectReply)
  })
_sym_db.RegisterMessage(ConnectReply)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.Input)
  })
_sym_db.RegisterMessage(Input)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.Output)
  })
_sym_db.RegisterMessage(Output)


DESCRIPTOR._options = None

_INTERACT = _descriptor.ServiceDescriptor(
  name='Interact',
  full_name='interaction.Interact',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=300,
  methods=[
  _descriptor.MethodDescriptor(
    name='SimpleConnect',
    full_name='interaction.Interact.SimpleConnect',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_CONNECTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SimpleSend',
    full_name='interaction.Interact.SimpleSend',
    index=1,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTERACT)

DESCRIPTOR.services_by_name['Interact'] = _INTERACT

# @@protoc_insertion_point(module_scope)
